---
title: "PySINDy: A comprehensive Python package for robust sparse system identification"
description: "Bringing nonlinear system identification to Python"
subtitle: "*Journal of Open Source Software*"
author: 
  - name: Alan A. Kaptanoglu
  - name: Brian M. de Silva
  - name: Urban Fasel
  - name: Kadierdan Kaheman
  - name: Andy J. Goldschmidt
  - name: Jared Callaham
  - name: Charles B. Delahunt
  - name: Zachary G. Nicolaou
  - name: Kathleen Champion
  - name: Jean-Christophe Loiseau
  - name: J. Nathan Kutz
  - name: Steven L. Brunton
date: "2022-01-29"
categories: [paper]
image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTcztYR1fxZqI2zk6pNGRiiR7Q-FIJCIStOg2TwQh0FA&s"
citation:
  type: article-journal
  container-title: "Journal of Open Source Software"
  doi: "10.21105/joss.03994"
  available-date: "2022-01-29"
  issued: "2022-01-29"
  volume: 7
  issue: 69
  page: 3994
  url: https://joss.theoj.org/papers/10.21105/joss.03994
google-scholar: true
---

<!--Include academic icons or bottons-->

{{< include /files/includes/_academic.qmd >}}


## Abstract

Automated data-driven modeling, the process of directly discovering the governing equations of a system from data, is increasingly being used across the scientific community.
`PySINDy` is a Python package that provides tools for applying the sparse identification of nonlinear dynamics (SINDy) approach to data-driven model discovery.
In this major update to `PySINDy`, we implement several advanced features that enable the discovery of more general differential equations from noisy and limited data.
The library of candidate terms is extended for the identification of actuated systems, partial differential equations (PDEs), and implicit differential equations.
Robust formulations, including the integral form of SINDy, and ensembling techniques, are also implemented to improve performance for real-word data.
Finally, we provide a range of new optimization algorithms, including several sparse regression techniques and algorithms to enforce and promote inequality constraints and stability.
Together, these updates enable entirely new SINDy model discovery capabilities that have not been reported in the literature, such as constrained PDE identification and ensembling with different sparse regression optimizers.

## Links

Published [paper](https://joss.theoj.org/papers/10.21105/joss.09623)


```{=html}
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div class="altmetric-embed" data-badge-popover="right" data-badge-type="donut" data-doi="10.21105/joss.03994"></div>

<span class="__dimensions_badge_embed__" data-doi="10.21105/joss.03994" data-hide-zero-citations="true" data-style="small_circle"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
```
