<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.34">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Jean-Christophe Loiseau">
<meta name="dcterms.date" content="2026-09-29">
<meta name="description" content="Quarto Academic Website Template adapted by Dr.&nbsp;Gang He">

<title>The roof, the roof, the roof is on fire! – Dr.&nbsp;Jean-Christophe Loiseau</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7ffecba3d65d0ceb76f4c7db622b63c9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-ee646ce384f049f4eccff96e17073bcf.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-1GNWFLTF2M"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-1GNWFLTF2M', { 'anonymize_ip': true});
</script>

<!-- 
Load Academicons v1: https://jpswalsh.github.io/academicons/
-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">


<!---
The following code are needed to show dimension citation and altmetrics.
https://api.altmetric.com/embeds.html
https://badge.dimensions.ai/
--->

<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>

<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="The roof, the roof, the roof is on fire! – Dr.&nbsp;Jean-Christophe Loiseau">
<meta property="og:description" content="A short introduction to performance engineering">
<meta property="og:image" content="https://loiseaujc.github.io/posts/blog-title/roofline.png">
<meta property="og:site_name" content="Dr. Jean-Christophe Loiseau">
<meta property="og:image:height" content="887">
<meta property="og:image:width" content="1774">
<meta name="twitter:title" content="The roof, the roof, the roof is on fire! – Dr.&nbsp;Jean-Christophe Loiseau">
<meta name="twitter:description" content="A short introduction to performance engineering">
<meta name="twitter:image" content="https://loiseaujc.github.io/posts/blog-title/roofline.png">
<meta name="twitter:image-height" content="887">
<meta name="twitter:image-width" content="1774">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Dr.&nbsp;Jean-Christophe Loiseau</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../posts.html#category=news">
 <span class="dropdown-text">News</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../posts.html#category=event">
 <span class="dropdown-text">Events</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../contact.html">
 <span class="dropdown-text">Contact</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-research" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Research</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-research">    
        <li>
    <a class="dropdown-item" href="../../publications.html">
 <span class="dropdown-text">List of Publications</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../posts.html#category=paper">
 <span class="dropdown-text">Selected Papers</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects.html">
 <span class="dropdown-text">Grants</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../teaching.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../people.html"> 
<span class="menu-text">Group</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html#category=blog"> 
<span class="menu-text">Blog: Ill-Conditioned Opinions</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../files/cv_loiseau.pdf"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/loiseaujc" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../posts.xml" target="_blank"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#a-simplistic-model-of-the-hardware" id="toc-a-simplistic-model-of-the-hardware" class="nav-link active" data-scroll-target="#a-simplistic-model-of-the-hardware">A simplistic model of the hardware</a>
  <ul class="collapse">
  <li><a href="#two-resources-computation-and-memory" id="toc-two-resources-computation-and-memory" class="nav-link" data-scroll-target="#two-resources-computation-and-memory">Two resources: computation and memory</a></li>
  <li><a href="#measuring-the-machine-with-likwid" id="toc-measuring-the-machine-with-likwid" class="nav-link" data-scroll-target="#measuring-the-machine-with-likwid">Measuring the machine with <code>likwid</code></a></li>
  </ul></li>
  <li><a href="#from-hardware-to-performance-the-roofline-model" id="toc-from-hardware-to-performance-the-roofline-model" class="nav-link" data-scroll-target="#from-hardware-to-performance-the-roofline-model">From hardware to performance: the roofline model</a>
  <ul class="collapse">
  <li><a href="#the-theoretical-roofline" id="toc-the-theoretical-roofline" class="nav-link" data-scroll-target="#the-theoretical-roofline">The theoretical roofline</a></li>
  <li><a href="#a-subtlety-the-roof-moves-with-the-problem-size" id="toc-a-subtlety-the-roof-moves-with-the-problem-size" class="nav-link" data-scroll-target="#a-subtlety-the-roof-moves-with-the-problem-size">A subtlety: the roof moves with the problem size</a></li>
  <li><a href="#so-what-about-jacobi-and-gauss-seidel-then" id="toc-so-what-about-jacobi-and-gauss-seidel-then" class="nav-link" data-scroll-target="#so-what-about-jacobi-and-gauss-seidel-then">So, what about Jacobi and Gauss-Seidel then?</a>
  <ul class="collapse">
  <li><a href="#our-kernels-have-low-ai." id="toc-our-kernels-have-low-ai." class="nav-link" data-scroll-target="#our-kernels-have-low-ai.">Our kernels have low AI.</a></li>
  <li><a href="#roofline-analysis-predicts-memory-bandwidth-is-the-binding-constraint." id="toc-roofline-analysis-predicts-memory-bandwidth-is-the-binding-constraint." class="nav-link" data-scroll-target="#roofline-analysis-predicts-memory-bandwidth-is-the-binding-constraint.">Roofline analysis predicts memory bandwidth is the binding constraint.</a></li>
  <li><a href="#lets-put-that-to-the-test." id="toc-lets-put-that-to-the-test." class="nav-link" data-scroll-target="#lets-put-that-to-the-test.">Let’s put that to the test.</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#where-does-that-leave-us" id="toc-where-does-that-leave-us" class="nav-link" data-scroll-target="#where-does-that-leave-us">Where does that leave us?</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The roof, the roof, the roof is on fire!</h1>
<p class="subtitle lead">A short introduction to performance engineering</p>
  <div class="quarto-categories">
    <div class="quarto-category">blog</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jean-Christophe Loiseau </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 29, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<center>
<hr width="50%" hr="">
</center>
<p><img src="roofline.png" class="img-fluid" style="width:100.0%"></p>
<center>
<hr width="50%" hr="">
</center>
<p>We made it! We finally ended up with an implementation of Gauss-Seidel that solves our test problem (marginally) faster than Jacobi while also preserving its parallelization capabilities. Last time, we concluded this success with a parallelization study and the results looked somewhat similar to what is depicted in the left panel of the figure below. If we stop there, we may come up with the following conclusion: every time we double the number of threads, the solver computes the solution twice as fast. No doubt that, for this particular test case – a 512 <span class="math inline">\(\times\)</span> 512 grid – it is effectively the case. If you don’t know any better, it may also be tempting to conclude that this scaling would hold true for larger grids. Or that, if I increase the number of points in each direction by 2 (so four times as many points), using four times as many threads would allow me to compute the solution in the same wallclock time. Pretty intuitive, right? But the right panel of this figure shows otherwise…</p>
<div id="9b6bcb4f" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="roofline_analysis_files/figure-html/cell-2-output-1.png" width="758" height="373" class="figure-img"></p>
<figcaption>Parallel speed-up for Jacobi and Red/Black Gauss-Seidel solvers relative to the ideal linear scaling on (a) small and (b) large computational grids. For each case, both kernels have performed 10 000 sweeps over the whole grid. Very different behaviours are observed. This is what we’ll be investigating in this post.</figcaption>
</figure>
</div>
</div>
</div>
<p>For the 512 <span class="math inline">\(\times\)</span> 512 grid, the scaling is almost perfect. Every time we double the number of threads, we get a 2<span class="math inline">\(\times\)</span> speed-up. But for the 2048 <span class="math inline">\(\times\)</span> 2048 grid, almost all of the speed-up happens between one and two threads. Further doubling the number of threads does absolutely nothing, so clearly our intuition is wrong. But why? Is there a bug in our code, or have we simply slammed into a physical boundary of our hardware? This is what we’ll try to unravel in this post.</p>
<section id="a-simplistic-model-of-the-hardware" class="level1 page-columns page-full">
<h1>A simplistic model of the hardware</h1>
<p>Processing units, whether CPU or GPU, are fantastic feats of modern technology. Just to give some intuition about how complex these can be, below is a block diagram of the AMD Bulldozer microprocessor.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ec/AMD_Bulldozer_block_diagram_%288_core_CPU%29.PNG/960px-AMD_Bulldozer_block_diagram_%288_core_CPU%29.PNG?utm_source=commons.wikimedia.org&amp;utm_campaign=index&amp;utm_content=thumbnail&amp;_=20140730203041" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>Block diagram of the AMD Bulldozer microprocessor (8 core CPU). Source: <a href="https://commons.wikimedia.org/wiki/File:AMD_Bulldozer_block_diagram_%288_core_CPU%29.PNG">Wikipedia Commons</a></figcaption>
</figure>
</div>
<p>Personally, I can’t really grasp all of the intricacies in this diagram. And mind you, this is a simplified representation, so I let you imagine how complex the true hardware can be! There is no way we can understand the different behaviour for the 512² and 2048² grids by tackling this level of hardware details head-on. We thus need to simplify things. And over-simplify we will.</p>
<section id="two-resources-computation-and-memory" class="level2">
<h2 class="anchored" data-anchor-id="two-resources-computation-and-memory">Two resources: computation and memory</h2>
<p>At a very, VERY high-level, CPUs can be understood as machines consuming two primary resources:</p>
<ul>
<li><strong>Compute</strong>: basically how fast the processor can run. It is typically measured in <em>billions of floating point operations per second</em> (Gflops/s).</li>
<li><strong>Memory bandwidth</strong>: essentially how quickly data can be transferred through the memory hierarchy. It is typically measured in <em>billions of bytes per second</em> (GBytes/s).</li>
</ul>
<p>In the rest of this post, we’ll actually consider two different types of memory, each with its own bandwidth:</p>
<ul>
<li><strong>DRAM</strong> (Dynamic Random-Access Memory): The main off-chip system memory that offers large storage capacity but exhibits high latency and limited bandwidth compared to on-chip caches.</li>
<li><strong>L3 Cache</strong>: A fast, shared on-chip buffer designed to store frequently accessed data close to the CPU cores to minimize latency-heavy requests to main memory (DRAM).</li>
</ul>
<p>With only these three elements, we arrive at the following (very) simplified block representation.</p>
<div id="a0e8d1c4" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="roofline_analysis_files/figure-html/cell-3-output-1.png" width="566" height="470" class="figure-img"></p>
<figcaption>Simplified execution model considering peak floating-point throughput (<span class="math inline">\(P_{\max}\)</span>) along with DRAM (<span class="math inline">\(BW_{\text{DRAM}}\)</span>) and L3 cache (<span class="math inline">\(BW_{\text{L3}}\)</span>) bandwidth constraints.</figcaption>
</figure>
</div>
</div>
</div>
<p>In the above diagram, <span class="math inline">\(P_{\max}\)</span> denotes the maximum number of floating point operations per second the processor can do, while <span class="math inline">\(BW_{\text{DRAM}}\)</span> and <span class="math inline">\(BW_{\text{L3}}\)</span> denote the bandwidths of the DRAM and L3 cache, respectively. I’ll be the first to admit: it is a tremendously gross over-simplification of the (already simplified) diagram presented earlier. Yet, it is surprising how far this simplified model of the hardware can take us in the analysis of our kernels’ performance. But before showing you that, let us put some concrete numbers on <span class="math inline">\(P_{\max}\)</span>, <span class="math inline">\(BW_{\text{DRAM}}\)</span> and <span class="math inline">\(BW_{\text{L3}}\)</span>.</p>
</section>
<section id="measuring-the-machine-with-likwid" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="measuring-the-machine-with-likwid">Measuring the machine with <code>likwid</code></h2>
<div class="page-columns page-full"><p>We could trust the vendors and get these numbers from their datasheet. However, these are often slightly optimistic estimates, so we’ll actually use some well-defined benchmarks to get more realistic values. For that purpose, we’ll use <a href="https://github.com/rrze-hpc/likwid"><code>likwid</code></a>: <em>a lightweight suite of command-line tools and a library designed for performance-oriented programming and hardware analysis on Linux systems</em>. <code>likwid</code> stands for <code>Like I Knew What I'm Doing</code>. It is developed by the same group behind <a href="https://github.com/RRZE-HPC/OSACA"><code>osaca</code></a>, the open-source code analyzer we used <a href="https://loiseaujc.github.io/posts/blog-title/make_gauss_seidel_great_again.html">here</a>. I won’t get into the details of how to install <code>likwid</code>, nor how to use its different utilities. The documentation is rather comprehensive, and the team has uploaded a handful of tutorial-style videos online (<a href="https://www.youtube.com/playlist?list=PLxVedhmuwLq2CqJpAABDMbZG8Whi7pKsk">here</a>). So with that out of the way, let’s get to it. </p><div class="no-row-height column-margin column-container"><span class="margin-aside">Everything that follows is me using <code>likwid</code> to the best of my understanding. If I’m doing anything wrong or misinterpreting something, feel free to reach out. I’d love to stand corrected.</span></div></div>
<p><strong>What does my hardware look like?</strong> First things first, let’s see what my hardware actually is. We’ll use <code>likwid-topology</code>, a dead simple utility printing the thread and cache topology on CPUs and GPUs. Here is what the output looks like for me.</p>
<pre><code>❯ likwid-topology 
--------------------------------------------------------------------------------
CPU name:   11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
CPU type:   Intel Tigerlake processor
CPU stepping:   1
********************************************************************************
Hardware Thread Topology
********************************************************************************
Sockets:        1
CPU dies:       1
Cores per socket:   8
Threads per core:   2
--------------------------------------------------------------------------------
HWThread        Thread        Core        Die        Socket        Available
0               0             0           0          0             *                
1               0             1           0          0             *                
2               0             2           0          0             *                
3               0             3           0          0             *                
4               0             4           0          0             *                
5               0             5           0          0             *                
6               0             6           0          0             *                
7               0             7           0          0             *                
8               1             0           0          0             *                
9               1             1           0          0             *                
10              1             2           0          0             *                
11              1             3           0          0             *                
12              1             4           0          0             *                
13              1             5           0          0             *                
14              1             6           0          0             *                
15              1             7           0          0             *                
--------------------------------------------------------------------------------
Socket 0:       ( 0 8 1 9 2 10 3 11 4 12 5 13 6 14 7 15 )
--------------------------------------------------------------------------------
********************************************************************************
Cache Topology
********************************************************************************
Level:          1
Size:           48 kB
Cache groups:       ( 0 8 ) ( 1 9 ) ( 2 10 ) ( 3 11 ) ( 4 12 ) ( 5 13 ) ( 6 14 ) ( 7 15 )
--------------------------------------------------------------------------------
Level:          2
Size:           1.25 MB
Cache groups:       ( 0 8 ) ( 1 9 ) ( 2 10 ) ( 3 11 ) ( 4 12 ) ( 5 13 ) ( 6 14 ) ( 7 15 )
--------------------------------------------------------------------------------
Level:          3
Size:           24 MB
Cache groups:       ( 0 8 1 9 2 10 3 11 4 12 5 13 6 14 7 15 )
--------------------------------------------------------------------------------
********************************************************************************
NUMA Topology
********************************************************************************
NUMA domains:       1
--------------------------------------------------------------------------------
Domain:         0
Processors:     ( 0 8 1 9 2 10 3 11 4 12 5 13 6 14 7 15 )
Distances:      10
Free memory:        19514.5 MB
Total memory:       31814.9 MB
--------------------------------------------------------------------------------</code></pre>
<div class="page-columns page-full"><p>There is a lot to unpack here, and more than we actually need. The most important points are: it is an Intel TigerLake processor, with a single socket, 8 cores per socket, and up to 2 threads per core. Additionally, the L3 cache size is 24 MB, shared across all the threads.  Moreover, since we can have two threads per core, we’ll use only every other thread to ensure 1 thread/core in the rest.</p><div class="no-row-height column-margin column-container"><span class="margin-aside">If you are familiar with Jacobi and performance engineering, you may already know why this 24 MB number is the key to our apparent mystery…</span></div></div>
<p><strong>How to evaluate <span class="math inline">\(P_{\max}\)</span>?</strong> To the raw performance now. We’ll use the <code>likwid-bench</code> utility, providing a large collection of standardized benchmarks to assess hardware performance. For peak performance, we’ll use <code>peakflops_avx_fma</code>. This kernel measures achievable (not marketed) peak double-precision throughput: it runs tight loops of independent, back-to-back FMA (fused multiply-add) instructions on a small working set (here, 32 kB) sized to stay resident in L1 cache. Since each FMA does 2 flops and the AVX2 FMA units on my CPU operate on 4 doubles at a time across two ports, this saturates the floating-point execution units and reports the sustained flops/s the core(s) can actually deliver. The estimate is typically somewhat below the vendor’s theoretical peak (turbo/clock throttling, instruction issue overhead, etc). Running it across thread counts gives the compute-scaling curve used to fix <span class="math inline">\(P_{\max}\)</span> later on.</p>
<p><strong>What about <span class="math inline">\(BW_{\text{DRAM}}\)</span> and <span class="math inline">\(BW_{\text{L3}}\)</span>?</strong> Again, we’ll use the <code>likwid-bench</code> utility, this time however with the <code>triad</code> benchmark. This kernel implements the classic STREAM Triad operation <code>a[i] = b[i] + s*c[i]</code>, over a large array. Because the arrays are always freshly loaded from memory or cache and immediately used once (dropped, not reused), the memory system – not the floating point units (FPU) – is the bottleneck. The benchmark thus reports sustained achievable bandwidth. Which level of the hierarchy gets stressed is controlled purely by working-set size: a 1 GB working set can’t fit in any cache on this processor, so it exercises DRAM bandwidth. Alternatively, an 8 MB working set fits inside the 24 MB shared L3, so it exercises L3 bandwidth instead. Same kernel, same thread-scaling sweep, two different memory levels depending on that one parameter.</p>
<div id="86e47be8" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="roofline_analysis_files/figure-html/cell-4-output-1.png" width="758" height="366" class="figure-img"></p>
<figcaption>Empirical hardware metrics collected via <code>likwid-bench</code> and averaged over 10 trials: (a) compute performance scaling compared to ideal, and (b) memory bandwidth saturation across 1 to 8 threads. The peak performance is estimated to be <strong>483 Gflops/s</strong>, while the memory bandwidth is around <strong>28 GBytes/s</strong> for DRAM, and at least <strong>417 GBytes/s</strong> for the L3 cache.</figcaption>
</figure>
</div>
</div>
</div>
<p>The figure above depicts the results of this hardware characterization experiment with an increasing number of threads being employed. Here are the most important take-aways:</p>
<ol type="1">
<li><strong>Compute scales (almost) linearly with threads; DRAM bandwidth basically doesn’t.</strong> Going from 1 to 8 threads roughly multiplies peak performance by 6.7 (from 76 Gflops/s to 484 Gflops/s), but DRAM bandwidth peaks at just 2 or 3 threads (~ 28 GBytes/s) and then decreases as more threads pile onto an already-saturated memory controller. A single thread already gets you most of the DRAM bandwidth this machine will ever offer. </li>
<li><strong>L3 bandwidth dwarfs DRAM bandwidth and shows no sign of saturating.</strong> At 8 threads, L3 delivers 416 GBytes/s against DRAM’s 23 GBytes/s – better than 15<span class="math inline">\(\times\)</span> more – and it’s still climbing at N=8 rather than plateauing. This gap is precisely why a problem that fits in L3 can keep scaling with threads long after a DRAM-resident problem has hit a wall.</li>
<li><strong>Compute’s own scaling isn’t quite “ideal” either.</strong> The measured curve in panel (a) already sits visibly below the ideal linear reference by 8 threads. This is a reminder that <span class="math inline">\(P_{\max}\)</span> itself softens as more cores turbo down together, so even the “good” resource isn’t a fixed constant once enough threads are in play.</li>
</ol>
<div class="no-row-height column-margin column-container"><span class="margin-aside">We’ll see later that this decline doesn’t seem to carry over to the Jacobi/Gauss-Seidel kernels themselves</span></div><p>We now have all of the numbers we need to characterize the hardware. Let’s move on with trying to model the performance of our kernels and see how our model compares with actual computations.</p>
</section>
</section>
<section id="from-hardware-to-performance-the-roofline-model" class="level1 page-columns page-full">
<h1>From hardware to performance: the roofline model</h1>
<p>We now have three numbers in hand: <span class="math inline">\(P_{\max}\)</span>, <span class="math inline">\(BW_{\text{DRAM}}\)</span>, and <span class="math inline">\(BW_{\text{L3}}\)</span>. But knowing your hardware’s ceilings doesn’t yet tell you how fast a <em>given</em> kernel should run. So let’s see how to do that.</p>
<section id="the-theoretical-roofline" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="the-theoretical-roofline">The theoretical roofline</h2>
<p><strong>Arithmetic intensity.</strong> The one ingredient missing is a way to characterize the kernel itself. For that, define the <em>arithmetic intensity</em> of a kernel as</p>
<p><span class="math display">\[
\text{AI} = \dfrac{\text{flops}}{\text{bytes moved}}.
\]</span></p>
<p>This is a property of the algorithm and its implementation, not of the hardware. A kernel that does a lot of arithmetic per byte it touches (high AI) can, in principle, keep the FPUs busy without waiting on memory. Conversely, a kernel that touches a lot of memory for very little arithmetic (low AI) will spend most of its time waiting on data, no matter how fast the processor is. Crucially, for a stencil kernel like Jacobi or Gauss-Seidel, both the flop count and the byte count per grid point are fixed by the discretization, so AI is a constant for the kernel. It does not depend on the grid size <span class="math inline">\(n\)</span>, only the sweep-level <em>cost</em> does.</p>
<p><strong>Resource allocation as a linear program.</strong> Here’s the idea. Rather than asking <em>what does the roofline plot look like</em>, let’s ask a more direct question: <em>given our three hardware ceilings and a kernel’s arithmetic intensity, what is the best throughput we could possibly hope for?</em> That’s an optimization problem, and a particularly simple one: a <a href="https://en.wikipedia.org/wiki/Linear_programming">linear program</a>.</p>
<p>Since we’ve been measuring everything in sweeps over the whole grid since the very first post, let’s keep using that unit rather than switching to raw Gflops/s. If <span class="math inline">\(f(n)\)</span> denotes the number of flops per sweep for a grid of size <span class="math inline">\(n\)</span>, then <span class="math inline">\(S = P/f(n)\)</span> converts a flop rate <span class="math inline">\(P\)</span> into sweeps per second. This is just a rescaling of the flop-based problem by the constant <span class="math inline">\(1/f(n)\)</span>, so it doesn’t change which constraint ends up binding. It just expresses the answer in units we already care about.</p>
<p>The resulting linear program reads</p>
<p><span class="math display">\[
\begin{aligned}
    \mathrm{maximize}   &amp;   \quad   S   \\
    \mathrm{subject~to} &amp;   \quad   S \cdot f(n) \leq P_{\max} \\
                        &amp;   \quad   S \cdot f(n) \leq  BW_{\text{DRAM}} \times AI.
\end{aligned}
\]</span></p>
<p>The first constraint says: no matter what, you can’t sweep faster than the processor can compute. The second says: no matter what, you can’t sweep faster than data can be fed to it from DRAM. This simplified model thus gives us an upper bound on the attainable throughput: whichever constraint is tighter is the active roof, exactly the <span class="math inline">\(\min\)</span> that gives the roofline its characteristic bent shape.</p>
<p><strong>Accounting for L3.</strong> The same reasoning that gave us the DRAM constraint applies to any level of the memory hierarchy a kernel’s working set happens to reside in – but not by adding a second, simultaneous bandwidth constraint. If the working set fits inside the 24 MB L3 cache, DRAM traffic becomes a one-off cost that gets amortized away over the many sweeps required by the solver to converge, so DRAM bandwidth simply isn’t part of the story for that grid size. Conversely, once the working set spills out of L3, every sweep pays the full cost of moving data from DRAM, and L3 residency isn’t happening at all. The two ceilings are mutually exclusive <em>regimes</em>, selected by problem size – not competitors in the same constraint.</p>
<p>This means we don’t need to change the structure of the LP at all: we only need to let the bandwidth ceiling itself depend on <span class="math inline">\(n\)</span>,</p>
<p><span class="math display">\[
BW(n)
=
\begin{cases}
    BW_{\text{L3}} &amp; \text{if the working set fits in L3}, \\
    BW_{\text{DRAM}} &amp; \text{otherwise},
\end{cases}
\]</span></p>
<p>giving the final LP formulation</p>
<div class="page-columns page-full"><p><span class="math display">\[
\begin{aligned}
    \mathrm{maximize}   &amp;   \quad   S   \\
    \mathrm{subject~to} &amp;   \quad   S \cdot f(n) \leq P_{\max} \\
                        &amp;   \quad   S \cdot f(n) \leq BW(n) \times AI
\end{aligned}
\]</span>  Rather than treating “L3-resident” and “DRAM-resident” as two separate stories requiring two separate analyses, they’re now a single feasible region whose second constraint simply looks up the right ceiling for the grid size at hand. Which constraint binds – compute, or whichever memory level is relevant – depends entirely on where your problem happens to sit, through <span class="math inline">\(n\)</span>’s effect on <span class="math inline">\(f(n)\)</span> and the working-set size. This is what will let a single model account for both panels of the very first figure in this post.</p><div class="no-row-height column-margin column-container"><span class="margin-aside">This now becomes a <em>parametric LP</em>. Nothing actually prevents us from further parameterizing <span class="math inline">\(P_\max\)</span> and <span class="math inline">\(BW(n)\)</span> as a function of the number of threads as well.</span></div></div>
</section>
<section id="a-subtlety-the-roof-moves-with-the-problem-size" class="level2">
<h2 class="anchored" data-anchor-id="a-subtlety-the-roof-moves-with-the-problem-size">A subtlety: the roof moves with the problem size</h2>
<p>If you’ve come across a roofline plot before, you’ve probably seen it used to compare several <em>different</em> kernels or algorithms, each sitting at its own arithmetic intensity, against a single fixed roof. Our situation is a little different, and worth walking through carefully: since <span class="math inline">\(AI\)</span> here is a property of the kernel alone, it doesn’t move as the grid size <span class="math inline">\(n\)</span> changes – your kernel sits at the exact same horizontal position on the plot no matter how big a problem you throw at it. What changes with <span class="math inline">\(n\)</span> is which <em>roof</em> is above that point.</p>
<p>Picture two roofline curves drawn on the same axes, sharing the same flat compute ceiling <span class="math inline">\(P_{\max}\)</span> but with two different sections: a higher sloped section governed by <span class="math inline">\(BW_{\text{L3}}\)</span>, and a lower one governed by <span class="math inline">\(BW_{\text{DRAM}}\)</span>. Because <span class="math inline">\(BW_{\text{L3}} \gg BW_{\text{DRAM}}\)</span>, the L3 roof’s ridge point sits much further to the left than the DRAM roof’s – meaning it takes a much lower <span class="math inline">\(AI\)</span> to be compute-bound under it. Jacobi and Gauss-Seidel are stencil kernels with a handful of flops per grid point against several bytes of neighbor data, which puts them at fairly low arithmetic intensity – plausibly low enough to sit on the sloped part of <em>both</em> roofs, not just the DRAM one. If that holds up once we compute the actual numbers in the next section, the real story isn’t “compute-bound at small <span class="math inline">\(n\)</span>, memory-bound at large <span class="math inline">\(n\)</span>” – it’s memory-bound throughout, just against two very different bandwidths. Either way, the mechanism is the same: nothing about the kernel changes as <span class="math inline">\(n\)</span> grows, but the ground shifts underneath it once the working set spills out of L3, and it’s this shift – from one sloped ceiling to a much lower one – that produces the two panels in this post’s opening figure.</p>
<div id="cf6ec162" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="roofline_analysis_files/figure-html/cell-5-output-1.png" width="758" height="374" class="figure-img"></p>
<figcaption>Schematic roofline plot with two memory ceilings. The same kernel, at a fixed arithmetic intensity (dotted vertical line), sits under two different roofs depending on which memory level its working set resides in. Here the kernel’s illustrative <span class="math inline">\(AI\)</span> is placed to the left of both ridge points, illustrating the case where a kernel is bandwidth-bound under either roof – just against a much faster bandwidth in one case than the other.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="so-what-about-jacobi-and-gauss-seidel-then" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="so-what-about-jacobi-and-gauss-seidel-then">So, what about Jacobi and Gauss-Seidel then?</h2>
<p>Now that we know what the roofline model is, the only missing pieces of information are the arithmetic intensities of both kernels. So let’s start with that.</p>
<section id="our-kernels-have-low-ai." class="level3">
<h3 class="anchored" data-anchor-id="our-kernels-have-low-ai.">Our kernels have low AI.</h3>
<p>As stated before, the arithmetic intensity (AI) is the ratio of the number of flops divided by the number of bytes moved from memory to actually perform these operations. It is important to note that this is for updating <strong>a single grid point</strong>. So let’s look at the two update rules again and start counting.</p>
<p><strong>Jacobi kernel.</strong> The update rule reads</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode numberSource fortran number-lines code-with-copy"><code class="sourceCode fortranfixed"><span id="cb2-1"><a href="#cb2-1"></a>u(i, j) <span class="kw">=</span> <span class="fl">0.25_dp</span> <span class="kw">*</span> (b(i, j)<span class="kw">*</span>dx2 <span class="kw">+</span> v(i<span class="kw">-</span><span class="dv">1</span>, j) <span class="kw">+</span> v(i<span class="kw">+</span><span class="dv">1</span>, j) <span class="kw">&amp;</span></span>
<span id="cb2-2"><a href="#cb2-2"></a>                                 <span class="kw">+</span> v(i, j<span class="kw">-</span><span class="dv">1</span>) <span class="kw">+</span> v(i, j<span class="kw">+</span><span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Let’s begin with the number of arithmetic operations because this is the easiest. We have 4 additions and 2 multiplications. So a grand total of 6 flops for a single grid point update.</p>
<p>Let’s move on with the number of bytes moved. These include both bytes fetch from memory (the right-hand side) and written to memory (storing the updated value). Naïve accounting would suggest:</p>
<ul>
<li>5 double-precision floating point numbers need to be fetched from memory (<code>b(i, j)</code>, <code>v(i+1, j)</code>, <code>v(i-1, j)</code>, <code>v(i, j+1)</code> and <code>v(i, j-1)</code>).</li>
<li>1 double-precision floating point number needs to be written to memory (<code>u(i, j)</code>).</li>
</ul>
<p>So that is a total of 6 double-precision floating point numbers, corresponding to 48 bytes per grid point. It is important to emphasize however that these 48 bytes are a strict upper bound that applies only in the worst case scenario, i.e.&nbsp;if every time we touch the values in <code>u</code>, <code>b</code> or <code>v</code>, they need to be fetched from memory. But compilers are smart. Not every reference to <code>v</code>, <code>b</code>, or <code>u</code> is a genuine trip to memory. Within a single sweep, <code>v(i, j)</code> gets referenced as a neighbor by up to 4 different point updates. If it’s still resident in cache from a few iterations ago (true here, since the sweep only needs 2–3 rows in flight at once), only the first of those references pays the memory cost; the rest are served from cache for free. On the other hand, the best scenario is every value is only fetched once from memory. That would give us 3 double-precision floating points numbers (<code>u(i, j)</code>, <code>b(i, j)</code> and <code>v(i, j)</code>) per update, for a grand total of 24 bytes. The actual truth is somewhere in between these two extremes, but we’ll go for the 24 bytes as, for these simple kernels, it is probably much more realistic.</p>
<p>It is now time to do some elementary school mathematics. For the Jacobi kernel, the arithmetic intensity is</p>
<p><span class="math display">\[
\text{AI} = \dfrac{6~\text{flops}}{24~\text{bytes moved}} = 0.25
\]</span></p>
<p>Not a very big number if you ask me, but it is what it is. It basically means that, for every arithmetic operation the kernel does, it needs to read or write 4 bytes from memory. For reference, had we considered the pessimistic upper bound, we would get an arithmetic intensity of 0.125 (so 8 bytes needed for every arithmetic operation).</p>
<p><strong>Gauss-Seidel.</strong> Time to move on with the Gauss-Seidel kernel</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode numberSource fortran number-lines code-with-copy"><code class="sourceCode fortranfixed"><span id="cb3-1"><a href="#cb3-1"></a>u(i, j) <span class="kw">=</span> <span class="fl">0.25_dp</span> <span class="kw">*</span> (b(i, j)<span class="kw">*</span>dx2 <span class="kw">+</span> u(i<span class="kw">+</span><span class="dv">1</span>, j) <span class="kw">+</span> u(i<span class="kw">-</span><span class="dv">1</span>, j) <span class="kw">&amp;</span></span>
<span id="cb3-2"><a href="#cb3-2"></a>                                 <span class="kw">+</span> u(i, j<span class="kw">+</span><span class="dv">1</span>) <span class="kw">+</span> u(i, j<span class="kw">-</span><span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>As far as flops go, the story is exactly the same: 4 additions and 2 multiplications, for a grand total of 6 flops. And it is the same for the memory traffic. Even though Gauss-Seidel uses only two buffers, it still needs to at least read the two arrays <code>b</code> and <code>u</code>, and to write the updated array <code>u</code> once. For the pessimistic case though, the bytes count is 48 bytes (5 loads and 1 write). And for the optimistic case, same as Jacobi again: 24 bytes (2 loads and 1 write). This leads to a lower bound of 24 bytes per grid point per sweep. Again, the actual truth is in-between, but we’ll use the optimistic bound again. This gives us the arithmetic intensity</p>
<p><span class="math display">\[
\text{AI} = \dfrac{6~\text{flops}}{24~\text{bytes}} = 0.25,
\]</span></p>
<p>the same as Jacobi.</p>
<p><strong>How much work is a sweep?</strong> For a standard roofline analysis, we could stop right there and proceed with the analysis itself. But because we’ve characterized everything so far in this series in terms of number of sweeps per second rather than raw Gflops/s, we need to account for that. This is precisely what the function <span class="math inline">\(f(n)\)</span> introduced earlier does. It is the number of flops per sweep, and it is the same for both Jacobi and Gauss-Seidel. Since <span class="math inline">\(n\)</span> is the number of points per direction (including the boundary ones), and both kernels require 6 flops per grid point, the total number of flops per sweep thus is</p>
<p><span class="math display">\[
f(n) = 6 \cdot (n-2)^2.
\]</span></p>
<p>For our two test grids, this works out to <span class="math inline">\(f(512)\)</span> = 1 560 600 flops/sweep, and <span class="math inline">\(f(2048)\)</span> = 25 116 696 flops/sweep. This is roughly the 16<span class="math inline">\(\times\)</span> jump you’d expect when quadrupling the resolution along each direction (so 16 times as many points).</p>
</section>
<section id="roofline-analysis-predicts-memory-bandwidth-is-the-binding-constraint." class="level3">
<h3 class="anchored" data-anchor-id="roofline-analysis-predicts-memory-bandwidth-is-the-binding-constraint.">Roofline analysis predicts memory bandwidth is the binding constraint.</h3>
<p>Alright, let’s move on with predicting the number of sweeps per second for each kernel. Note that we don’t actually need a solver for the linear program. You can easily convince yourself that the solution is given by</p>
<p><span class="math display">\[
S = \min \left( \dfrac{P_\max}{f(n)}, \dfrac{BW(n) \times AI}{f(n)} \right).
\]</span></p>
<p>Modulo the <span class="math inline">\(1 / f(n)\)</span> scaling to transform Gflops/s into sweeps/s, this is exactly the expression you’d find if you look up <em>roofline analysis</em> on the internet. So let’s put some numbers in. We’ll assume for now that we use all 8 threads so that the <code>likwid</code> estimates for <span class="math inline">\(P_{\max}\)</span> and <span class="math inline">\(BW(n)\)</span> are</p>
<ul>
<li><span class="math inline">\(P_\max = 483\)</span> Gflops/s</li>
<li><span class="math inline">\(BW(n) = 417\)</span> Gbytes/s if the problem fits entirely in the L3 cache, or <span class="math inline">\(BW(n) = 28.5\)</span> Gbytes/s otherwise.</li>
</ul>
<p>Plugging-in the expression for <span class="math inline">\(f(n)\)</span> and the arithmetic intensities of the two kernels, we get the following for the 2048² grid.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Kernel</th>
<th style="text-align: center;">Maximum number of sweeps per second</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Jacobi</td>
<td style="text-align: center;">279</td>
</tr>
<tr class="even">
<td style="text-align: center;">Gauss-Seidel</td>
<td style="text-align: center;">279</td>
</tr>
</tbody>
</table>
<p>Let’s use the actual roofline plot to make sense of these.</p>
<div id="b35dbfe4" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="roofline_analysis_files/figure-html/cell-6-output-1.png" width="757" height="371" class="figure-img"></p>
<figcaption>Theoretical roofline analysis for the two kernels. Peak performance and DRAM bandwidth estimates have been obtained using <code>likwid</code>, while the number of grid points in the problem is 2048².</figcaption>
</figure>
</div>
</div>
</div>
<p>The two kernels sit very comfortably along the slanted line, corresponding to the memory-bound region. For the 2048² grid, DRAM bandwidth is thus the limiting factor here for both. The picture would have essentially been the same had we consider the 512², with the DRAM bandwidth simply replaced by that of the L3 cache. But are these predictions any good?</p>
</section>
<section id="lets-put-that-to-the-test." class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="lets-put-that-to-the-test.">Let’s put that to the test.</h3>
<section id="do-the-predictions-match-the-effective-number-of-sweepss-measured-numerically" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="do-the-predictions-match-the-effective-number-of-sweepss-measured-numerically">Do the predictions match the effective number of sweeps/s measured numerically?</h4>
<p>Let us consider only the 2048² case for now. The experimental setup is as follows: both kernels are compiled with <code>gfortran -O3 -mtune=native -march=native -fopenmp -ftree-loop-vectorize=8</code> to enable vectorization and full multithreading over the 8 physical cores of my laptop. We run both kernels 10 000 times, measure how long it takes, and extract the number of sweeps per second. Simple enough, right? So here are the results.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Kernel</th>
<th style="text-align: center;">Predicted number of sweeps per second</th>
<th style="text-align: center;">Measured number of sweeps per second</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Jacobi</td>
<td style="text-align: center;">279</td>
<td style="text-align: center;">272</td>
</tr>
<tr class="even">
<td style="text-align: center;">Gauss-Seidel</td>
<td style="text-align: center;">279</td>
<td style="text-align: center;">219</td>
</tr>
</tbody>
</table>
<p>And look at those numbers for Jacobi! The model predicts 279 sweeps per second, the actual experiment reports 272. Despite how simple our model is, it nails it. But the agreement for Gauss-Seidel ain’t that good though. We’re off by 20% or so. So what is going on here?</p>
<p>To partially explain this observation, we need to go back to the full kernel. So here it is.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode numberSource fortran number-lines code-with-copy"><code class="sourceCode fortranfixed"><span id="cb4-1"><a href="#cb4-1"></a><span class="kw">do</span> k <span class="kw">=</span> <span class="dv">0</span>, <span class="dv">1</span></span>
<span id="cb4-2"><a href="#cb4-2"></a>    <span class="kw">do</span> j <span class="kw">=</span> <span class="dv">2</span>, n<span class="kw">-</span><span class="dv">1</span></span>
<span id="cb4-3"><a href="#cb4-3"></a>        istart <span class="kw">=</span> <span class="dv">2</span> <span class="kw">+</span> <span class="bu">mod</span>(k<span class="kw">+</span>j, <span class="dv">2</span>)</span>
<span id="cb4-4"><a href="#cb4-4"></a>        <span class="kw">do</span> i <span class="kw">=</span> istart, n<span class="kw">-</span><span class="dv">1</span>, <span class="dv">2</span></span>
<span id="cb4-5"><a href="#cb4-5"></a>            u(i, j) <span class="kw">=</span> <span class="fl">0.25_dp</span> <span class="kw">*</span> (b(i, j)<span class="kw">*</span>dx2 <span class="kw">+</span> u(i<span class="kw">+</span><span class="dv">1</span>, j) <span class="kw">+</span> u(i<span class="kw">-</span><span class="dv">1</span>, j) <span class="kw">&amp;</span></span>
<span id="cb4-6"><a href="#cb4-6"></a>                                             <span class="kw">+</span> u(i, j<span class="kw">+</span><span class="dv">1</span>) <span class="kw">+</span> u(i, j<span class="kw">-</span><span class="dv">1</span>))</span>
<span id="cb4-7"><a href="#cb4-7"></a>        <span class="kw">end do</span></span>
<span id="cb4-8"><a href="#cb4-8"></a>    <span class="kw">end do</span></span>
<span id="cb4-9"><a href="#cb4-9"></a><span class="kw">end do</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="page-columns page-full"><p>See what’s happening here? We’re looping over the whole arrays twice, but that is not the issue. What really matters is that we read and write only every other point. I’m not an expert on CPU but, apparently, when a CPU writes to a cache line that isn’t already resident, it normally has to first read the full 64-byte line from memory before it can modify the 8 bytes you actually wanted to change. It can’t write a partial line without knowing what the rest of it contains. This is the write-allocate / read-for-ownership cost (RFO), and it’s a real, extra 8 bytes on top of the write itself. So the effective number of bytes moved is not 24 but 32.  And consequently, the corresponding arithmetic intensity decreases from 0.25 (our initial estimate) down to 0.1875 – worse than Jacobi. If you redo the math with this new AI, you would find a theoretical maximum of 209 sweeps per second so… our model nailed it again (after we’ve accounted for the read-for-ownership extra bytes)!</p><div class="no-row-height column-margin column-container"><span class="margin-aside">Is this the whole story? I don’t know, but it certainly seems like a very plausible explanation.</span></div></div>
</section>
<section id="extending-our-model-to-include-the-number-of-threads" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="extending-our-model-to-include-the-number-of-threads">Extending our model to include the number of threads</h4>
<div class="page-columns page-full"><p>So our model works remarkably well for the 8 threads computations and predicts that, for the 2048² grid, both kernels are memory-bound. But does it correctly predict the number of sweeps per second if we keep the grid constant but vary the number of threads used from 1 to 8? Let’s find out! The only modification we need to make is that the peak performance <span class="math inline">\(P_{\max}\)</span> and bandwidths <span class="math inline">\(BW\)</span> now depend on the number <span class="math inline">\(T\)</span> of threads.  So here are the results.</p><div class="no-row-height column-margin column-container"><span class="margin-aside">Plugging in the measured Triad bandwidth curve directly here (which declines past 2-3 threads, as we saw earlier) makes the model <em>under</em>-predict at high thread counts. Measured throughput ends up exceeding the predicted ceiling by up to 25%, which shouldn’t happen for what’s meant to be an upper bound. Holding DRAM bandwidth flat at roughly its 2-3-thread peak (~28.5 GBytes/s) instead of letting it decline fixes this for both kernels at once, which is a stronger signal than it might look: it suggests the standalone Triad benchmark’s falling bandwidth at 6-8 threads isn’t representative of what these stencil kernels actually sustain. One possible explanation is that Triad’s back-to-back streaming loads leave the memory controller no compute-induced gaps to work with, unlike a kernel doing 6 flops of dependent arithmetic per point. The rigorous way to settle this would be measuring DRAM traffic directly during the Jacobi/GS runs themselves (e.g.&nbsp;with <code>likwid-perfctr</code>’s memory group) rather than borrowing the number from Triad – on the list for a follow-up.</span></div></div>
<div id="f57f4a6e" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="roofline_analysis_files/figure-html/cell-7-output-1.png" width="758" height="371" class="figure-img"></p>
<figcaption>Number of sweeps per second as a function of the number of threads being used for two different grids. (a) For a 512² grid, all the data fit comfortably in the L3 cache. (b) For a 2048², the data exceeds the L3 cache and data movement mostly come from DRAM.</figcaption>
</figure>
</div>
</div>
</div>
<p>And there you have it! It looks very much like the very first figure in this post, but now we can come up with an explanation. The two kernels are memory-bound for both grid resolutions. For the smaller grid though, all the data fit comfortably inside the L3 cache. As a consequence, the almost linear speed-up observed as we crank up the number of threads is directly related to the increasing L3 bandwidth obtained with increasing threads count already observed when benchmarking the hardware with <code>likwid</code>. To be completely honest, this holds up well for Jacobi throughout, but the fit for Gauss-Seidel visibly worsens as thread count grows. The predicted and measured sweep rates diverge by close to 50% at 7-8 threads, suggesting the simple read-for-ownership correction that worked so well for the DRAM-bound case does not transfer cleanly to the L3-bound regime. Very likely, the details of L3 traffic are more complicated than what can be accounted for with our ridiculously simple model. Nonetheless, the predictions are still in the correct ballpark, which is good enough in my opinion given how simple our model is.</p>
<p>For the larger grid, the working set no longer fits in L3, so DRAM becomes the dominant memory level. But again, the jump observed when moving from 1 to 2 threads can be entirely explained by the increase in DRAM bandwidth reported with <code>likwid</code>. For larger thread counts, this DRAM bandwidth however saturates. And since the two kernels are memory-bound anyway, the increased peak performance observed for increased thread counts cannot kick in. The number of sweeps per second thus saturates also to roughly 270 sweeps/s for Jacobi and 210 sweeps/s for the red/black Gauss-Seidel kernel. Mystery solved.</p>
</section>
</section>
</section>
</section>
<section id="where-does-that-leave-us" class="level1 page-columns page-full">
<h1>Where does that leave us?</h1>
<p>I told you: oversimplify we will, and oversimply we have! I’ll be the first to admit: our model of the hardware is ridiculously simple. Yet, I am still amazed at how good its predictions are (most notably for the larger grid size). The main take-away however is that <strong>both kernels run essentially as fast as they possibly can on my hardware</strong>. So, have we finally reached the end of the road?</p>
<div class="page-columns page-full"><p>Well… not quite yet. But we’re getting there, trust me (I’m a Doctor). Going back to Gflops/s, Gauss-Seidel and Jacobi achieve something like 5 and 7 Gflops/s on my laptop. This is 70 to 90 times less than what my CPU can deliver. That is an enormous amount of idle compute capacity just sitting there, unused precisely because we’re memory-bound. The next lever for increased performance isn’t however the one people usually reach for first. The instinct here is often “try loop tiling,” but ordinary spatial tiling can’t fundamentally help: it works by improving cache reuse within a sweep, but we already achieve near-ideal reuse for Jacobi. There’s no further reuse to extract from a single pass over the grid. For Gauss-Seidel, measured throughput is likely close to its floor too, but the read-for-ownership story suggests there may be a few percent left on the table from smarter store handling (outside the scope of what a bytes-moved model alone can settle). The opening isn’t spatial, it’s temporal. But we won’t be going down this road, so look for diamond tiling, trapezoidal decompositions, and wavefront schedules if you want to know more. </p><div class="no-row-height column-margin column-container"><span class="margin-aside">It is fascinating, but I have no idea how to introduce such complex techniques in a short blog post. If you do, please get started, I’ll be the first to read it!</span></div></div>
<p>So where does that leave us? Well, since we can’t easily increase the number of sweeps per second for these kernels, how about finding out some way to reduce the number of sweeps needed to solve the problem in the first place? This is what will be coming next. And it’s called SOR…</p>
<!--Include social share buttons-->
<!-- 
AddToAny check more: https://www.addtoany.com/buttons/for/website 
Using includes will make edits easier, will only need to add or remove button here if needed.
https://quarto.org/docs/authoring/includes.html
-->
<div class="a2a_kit a2a_kit_size_32 a2a_default_style">
<p><a class="a2a_dd" href="https://www.addtoany.com/share"></a> <a class="a2a_button_linkedin"></a> <a class="a2a_button_bluesky"></a> <a class="a2a_button_facebook"></a> <a class="a2a_button_copy_link"></a> <a class="a2a_button_email"></a></p>
</div>
<script async="" src="https://static.addtoany.com/menu/page.js"></script>
<hr>
<p><strong>If you want to read more of my stuff</strong></p>
<ul>
<li><a href="https://loiseaujc.github.io/posts/blog-title/redblack_gauss_seidel.html">Red or Black?</a></li>
<li><a href="https://loiseaujc.github.io/posts/blog-title/make_gauss_seidel_great_again.html">Make Gauss-Seidel great again!</a></li>
<li><a href="https://loiseaujc.github.io/posts/blog-title/gauss_seidel_experiments.html">Gauss-Seidel is faster than Jacobi. Or is it?</a></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("^(?:http:|https:)\/\/drganghe\.github\.io\/custom");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "loiseaujc/loiseaujc.github.io";
    script.dataset.repoId = "R_kgDOPsMNvw";
    script.dataset.category = "General";
    script.dataset.categoryId = "DIC_kwDOPsMNv84CvT6M";
    script.dataset.mapping = "title";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="http://www.github.com">Jean-Christophe Loiseau</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
<p>Build on <a href="https://github.com/drganghe/quarto-academic-website-template">Quart Academic Website Template</a> adapted by <a href="http://drganghe.github.io">Dr.&nbsp;Gang He</a></p>
</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/drganghe/quarto-academic-website-template" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank">
<p><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></p>
</a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="../../posts.xml" target="_blank">
      <i class="bi bi-rss" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>